variables:
  HELM_VERSION: 2.7.2
  KUBECTL_VERSION: 1.11.0

build-and-push:
  image: docker:git
  services:
    - docker:dind
  variables:
    DOCKER_DRIVER: overlay2
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"
  script:
    - export IMAGE_WITH_TAG="$CI_REGISTRY_IMAGE/releases/$HELM_VERSION-kube-$KUBECTL_VERSION"
    - docker build --build-arg "HELM_VERSION=$HELM_VERSION" --build-arg "KUBECTL_VERSION=$KUBECTL_VERSION" --tag "$IMAGE_WITH_TAG" .
    - docker push "$IMAGE_WITH_TAG"
  only:
    - master
